# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('pickled_model', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
