# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agegroup_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainedModel',
            new_name='Pickle',
        ),
    ]
